# from fbchat import Client
# from fbchat.models import *

# client = Client('email', 'password')

# print('my Id: {}'.format(client.uid))

# client.send(Message(text='Hi me !'), thread_id=client.uid, thread_type=ThreadType.USER)

# # Find out the userID from this -> searchForUsers(name, limit=1); limit -> max number of result to fetch
# #client.searchForUsers('shimanto')
# #Sazid Islam Araf: 100005668656973
# # imam vai: 1574280616


# client.send(Message(text='Hi! This is an autogenerated message'), thread_id=client.uid, thread_type=ThreadType.USER)


from fbchat import log, Client
from fbchat.models import *
import sys

username = sys.argv[1]
password = sys.argv[2]

# client.searchForUsers('shimanto')
# Change this to id
old_thread_id = '1574280616'

# Change these to match your liking
old_color = ThreadColor.MESSENGER_BLUE
old_emoji = '👍'
old_title = 'Old group chat name'
old_nicknames = {
    '1574280616': "Syed Imam Hasan",
    '100000068462641': "Shariful Foysal"
}


# '1574280616': "Syed Imam Hasan",
#    ...:     '100000068462641': "Shariful Islam Foysal"

class KeepBot(Client):
    def onColorChange(self, author_id, new_color, thread_id, thread_type, **kwargs):
        if old_thread_id == thread_id and old_color != new_color:
            log.info("{} changed the thread color. It will be changed back".format(author_id))
            self.changeThreadColor(old_color, thread_id=thread_id)

    def onEmojiChange(self, author_id, new_emoji, thread_id, thread_type, **kwargs):
        if old_thread_id == thread_id and new_emoji != old_emoji:
            log.info("{} changed the thread emoji. It will be changed back".format(author_id))
            self.changeThreadEmoji(old_emoji, thread_id=thread_id)

    def onNicknameChange(self, author_id, changed_for, new_nickname, thread_id, thread_type, **kwargs):
        if old_thread_id == thread_id and changed_for in old_nicknames and old_nicknames[changed_for] != new_nickname:
            log.info("{} changed {}'s' nickname. It will be changed back".format(author_id, changed_for))
            self.changeNickname(old_nicknames[changed_for], changed_for, thread_id=thread_id, thread_type=thread_type)

client = KeepBot(username, password)
client.listen()